/*
 * daemon/ebpf/uprobes/test/host_ctx_test.c
 *
 * Integration test for host_ctx.bpf.c — the cuLaunchKernel uprobe.
 *
 * WHAT THIS FILE DOES:
 *   1. Loads host_ctx.bpf.o into the kernel (Level 1+2: compile + verifier).
 *   2. Attaches the probe to cuLaunchKernel in libcuda.so (Level 3: attach).
 *   3. Forks and execs a CUDA fixture binary (k1) as a child process.
 *      The fixture calls cuLaunchKernel in a loop — that's the trigger.
 *   4. Polls the ring buffer while the child runs, collecting events.
 *   5. Filters events down to the child's PID so other CUDA processes
 *      on the same machine don't pollute the assertions.
 *   6. After the child exits, drains any remaining events, then asserts:
 *        - at least WEDJAT_ITERS events arrived (one per launch)
 *        - every event has a non-zero timestamp
 *        - every event has a non-empty comm string
 *        - every event has grid_x > 0 and a valid block_x (Level 4).
 *
 * HOW TO BUILD (once host_ctx.skel.h exists):
 *   See test/Makefile — the skeleton is generated by bpftool, then this
 *   file is compiled with clang -lbpf.
 *
 * HOW TO RUN:
 *   sudo ./bin/host_ctx_test k1
 *   sudo ./bin/host_ctx_test k2
 *
 *   Requires root (CAP_BPF + CAP_PERFMON) and a real GPU.
 *   k1/k2 must already be built: make -C ../../../../kernels_to_trace build
 *
 * CURRENT STATE:
 *   The BPF skeleton (host_ctx.skel.h) does not exist yet — it is generated
 *   from host_ctx.bpf.o once host_ctx.bpf.c compiles cleanly.  The real
 *   loader/attach/ringbuf blocks are inside TODO comments below so the shape
 *   is visible.  The fork/exec/waitpid skeleton is fully real and compiles
 *   today without libbpf.
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

/*
 * When host_ctx.skel.h exists, uncomment these three includes and remove the
 * stub struct/defines at the bottom of this file.
 *
 * #include <bpf/libbpf.h>
 * #include "host_ctx.skel.h"
 * #include "../../wedjat_common.h"
 */

/* ============================================================
 * ASSERTION MACROS
 *
 * Lightweight — no framework needed.  Each macro prints a human-readable
 * failure message and returns 1 from the enclosing function on failure.
 * ============================================================ */

/* Assert a boolean condition is true. */
#define ASSERT_TRUE(cond, msg)                                          \
    do {                                                                \
        if (!(cond)) {                                                  \
            fprintf(stderr, "FAIL [%s:%d]: %s\n",                      \
                    __FILE__, __LINE__, (msg));                         \
            return 1;                                                   \
        }                                                               \
    } while (0)

/* Assert two integer values are equal. */
#define ASSERT_EQ(actual, expected, msg)                                \
    do {                                                                \
        if ((actual) != (expected)) {                                   \
            fprintf(stderr, "FAIL [%s:%d]: %s (got %ld, want %ld)\n",  \
                    __FILE__, __LINE__, (msg),                          \
                    (long)(actual), (long)(expected));                  \
            return 1;                                                   \
        }                                                               \
    } while (0)

/* Assert actual >= expected. */
#define ASSERT_GE(actual, expected, msg)                                \
    do {                                                                \
        if ((actual) < (expected)) {                                    \
            fprintf(stderr, "FAIL [%s:%d]: %s (got %ld, want >= %ld)\n",\
                    __FILE__, __LINE__, (msg),                          \
                    (long)(actual), (long)(expected));                  \
            return 1;                                                   \
        }                                                               \
    } while (0)

/* ============================================================
 * EVENT STRUCT (stub until wedjat_common.h is filled in)
 *
 * Must match the layout of struct launch_event in host_ctx.bpf.c exactly.
 * When wedjat_common.h defines it, remove this duplicate.
 * ============================================================ */
struct launch_event {
    unsigned long long timestamp_ns;
    unsigned int       pid;
    unsigned int       tid;
    char               comm[16];
    unsigned int       grid_x;
    unsigned int       grid_y;
    unsigned int       grid_z;
    unsigned int       block_x;
    unsigned int       block_y;
    unsigned int       block_z;
    unsigned int       _pad;
};

/* ============================================================
 * TEST STATE
 *
 * Global so the ring buffer callback (handle_event) can update it without
 * needing to pass a context pointer through libbpf's callback API.
 * ============================================================ */
static int   g_events_seen = 0;   /* total events from our child's PID      */
static int   g_assert_failed = 0; /* set to 1 if any per-event assertion fails */
static pid_t g_fixture_pid = -1;  /* child PID — events from other PIDs ignored */

/* ============================================================
 * RING BUFFER CALLBACK
 *
 * Called by ring_buffer__poll() once for each event in the buffer.
 * We filter on PID so other CUDA activity on the box is ignored.
 *
 * Returns 0 to keep consuming, non-zero to stop.
 * ============================================================ */

/*
 * TODO: uncomment when skeleton exists.
 *
 * static int handle_event(void *ctx, void *data, size_t sz)
 * {
 *     (void)ctx;
 *     if (sz < sizeof(struct launch_event))
 *         return 0;
 *
 *     struct launch_event *e = (struct launch_event *)data;
 *
 *     // Ignore events from processes other than our CUDA fixture child.
 *     if (e->pid != (unsigned int)g_fixture_pid)
 *         return 0;
 *
 *     g_events_seen++;
 *
 *     // Per-event Level 4 assertions.
 *     if (e->timestamp_ns == 0) {
 *         fprintf(stderr, "FAIL: event %d has zero timestamp\n", g_events_seen);
 *         g_assert_failed = 1;
 *     }
 *     if (e->comm[0] == '\0') {
 *         fprintf(stderr, "FAIL: event %d has empty comm\n", g_events_seen);
 *         g_assert_failed = 1;
 *     }
 *     if (e->grid_x == 0) {
 *         fprintf(stderr, "FAIL: event %d has grid_x == 0\n", g_events_seen);
 *         g_assert_failed = 1;
 *     }
 *     if (e->block_x == 0 || e->block_x > 1024) {
 *         fprintf(stderr, "FAIL: event %d has invalid block_x=%u\n",
 *                 g_events_seen, e->block_x);
 *         g_assert_failed = 1;
 *     }
 *
 *     return 0;
 * }
 */

/* ============================================================
 * FIXTURE RUNNER
 *
 * Forks a child process and execs the given CUDA fixture binary.
 * Sets WEDJAT_ITERS and WEDJAT_SLEEP_MS low so the test runs fast.
 *
 * Returns the child PID on success, -1 on error.
 * ============================================================ */
static pid_t run_fixture(const char *binary_path, int iters, int sleep_ms)
{
    pid_t pid = fork();
    if (pid < 0) {
        perror("fork");
        return -1;
    }

    if (pid == 0) {
        /*
         * Child process.
         *
         * Set the knobs low so the fixture finishes in a few seconds.
         * WEDJAT_ITERS controls how many cuLaunchKernel calls k1 makes,
         * so ASSERT_EQ(g_events_seen, iters) can be exact.
         */
        char iters_str[16], sleep_str[16];
        snprintf(iters_str,  sizeof(iters_str),  "%d", iters);
        snprintf(sleep_str,  sizeof(sleep_str),  "%d", sleep_ms);
        setenv("WEDJAT_ITERS",    iters_str, 1);
        setenv("WEDJAT_SLEEP_MS", sleep_str, 1);

        execl(binary_path, binary_path, (char *)NULL);
        perror("execl");
        _exit(127);
    }

    return pid;
}

/* ============================================================
 * TEST FUNCTION
 *
 * Runs one full load → attach → trigger → assert cycle.
 * Returns 0 on pass, 1 on failure.
 * ============================================================ */
static int test_cu_launch_kernel_emits_identity(const char *fixture_path)
{
    /*
     * Number of iterations to tell k1 to run.
     * We assert exactly this many events arrive.
     * Keep it small (3) so the test is fast.
     */
    const int expected_iters = 3;

    printf("TEST cu_launch_kernel_emits_identity fixture=%s iters=%d\n",
           fixture_path, expected_iters);

    /* -------------------------------------------------------
     * Level 1+2: load BPF object into kernel.
     *
     * host_ctx_bpf__open_and_load() is generated by bpftool from
     * host_ctx.bpf.o.  It:
     *   - opens the ELF object
     *   - pins maps
     *   - calls the BPF verifier
     * If the verifier rejects the program, this returns NULL.
     *
     * TODO: uncomment when skeleton exists.
     *
     * struct host_ctx_bpf *skel = host_ctx_bpf__open_and_load();
     * ASSERT_TRUE(skel != NULL, "failed to load BPF skeleton");
     * ------------------------------------------------------- */

    /* -------------------------------------------------------
     * Level 3: attach uprobe to cuLaunchKernel in libcuda.so.
     *
     * We attach by library path + symbol name.  The kernel resolves
     * the symbol offset at attach time — we never hardcode offsets
     * because libcuda.so.1 changes with every driver version.
     *
     * -1 as the PID means "attach to all processes" (system-wide).
     * We filter down to our child's PID in handle_event instead of
     * attaching per-PID, because we fork after attaching and we
     * can't know the child's PID before the fork.
     *
     * TODO: uncomment when skeleton exists.  Find the real libcuda
     * path with:  ldconfig -p | grep libcuda
     *
     * const char *libcuda = "/usr/lib/x86_64-linux-gnu/libcuda.so.1";
     * struct bpf_uprobe_opts uopts = {
     *     .sz        = sizeof(uopts),
     *     .func_name = "cuLaunchKernel",
     *     .retprobe  = false,
     * };
     * struct bpf_link *link = bpf_program__attach_uprobe_opts(
     *     skel->progs.handle_cu_launch_kernel, -1, libcuda, 0, &uopts);
     * ASSERT_TRUE(link != NULL, "failed to attach uprobe to cuLaunchKernel");
     * ------------------------------------------------------- */

    /* -------------------------------------------------------
     * Open ring buffer reader.
     *
     * ring_buffer__new registers handle_event as the callback.
     * ring_buffer__poll() calls it for each pending event.
     *
     * TODO: uncomment when skeleton exists.
     *
     * struct ring_buffer *rb = ring_buffer__new(
     *     bpf_map__fd(skel->maps.events), handle_event, NULL, NULL);
     * ASSERT_TRUE(rb != NULL, "failed to open ring buffer");
     * ------------------------------------------------------- */

    /* -------------------------------------------------------
     * Spawn the CUDA fixture as a child process.
     * After this point g_fixture_pid is set so handle_event
     * knows which PID to accept.
     * ------------------------------------------------------- */
    g_fixture_pid = run_fixture(fixture_path, expected_iters, 20);
    ASSERT_TRUE(g_fixture_pid > 0, "failed to fork CUDA fixture");

    /* -------------------------------------------------------
     * Poll the ring buffer while the child is running.
     *
     * We loop on waitpid(WNOHANG) + ring_buffer__poll so we drain
     * the buffer continuously instead of letting it fill up while
     * waiting for the child to exit.
     *
     * TODO: replace the sleep loop with real poll once skeleton exists.
     *
     * int wstatus;
     * while (waitpid(g_fixture_pid, &wstatus, WNOHANG) == 0)
     *     ring_buffer__poll(rb, 100);  // 100 ms timeout per poll
     *
     * // Final drain: catch any events emitted just before exit.
     * ring_buffer__poll(rb, 200);
     * ------------------------------------------------------- */

    /* Placeholder: just wait for the child with no probe active yet. */
    int wstatus;
    if (waitpid(g_fixture_pid, &wstatus, 0) < 0) {
        perror("waitpid");
        return 1;
    }

    /* -------------------------------------------------------
     * Assert the fixture itself exited cleanly.
     * A non-zero exit means the CUDA program failed (bad GPU,
     * driver error, etc.) — not a probe failure.
     * ------------------------------------------------------- */
    ASSERT_TRUE(WIFEXITED(wstatus),          "fixture did not exit normally");
    ASSERT_EQ(WEXITSTATUS(wstatus), 0,       "fixture exited with non-zero status");

    /* -------------------------------------------------------
     * Level 4: assert on captured events.
     *
     * TODO: uncomment when skeleton exists.
     *
     * ASSERT_TRUE(!g_assert_failed,           "per-event assertions failed");
     * ASSERT_EQ(g_events_seen, expected_iters,"wrong number of launch events");
     * ------------------------------------------------------- */

    fprintf(stderr, "SKIP: BPF skeleton not generated yet — probe assertions not active\n");

    /* -------------------------------------------------------
     * Cleanup.
     *
     * TODO: uncomment when skeleton exists.
     *
     * ring_buffer__free(rb);
     * bpf_link__destroy(link);
     * host_ctx_bpf__destroy(skel);
     * ------------------------------------------------------- */

    printf("SKIP cu_launch_kernel_emits_identity (skeleton missing)\n");
    return 0;
}

/* ============================================================
 * ENTRY POINT
 *
 * Usage: sudo ./bin/host_ctx_test <fixture>
 *   <fixture> is k1, k2, etc. — name only, not full path.
 *   The full path is built as ../../../../kernels_to_trace/build/<fixture>.
 * ============================================================ */
int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <fixture>\n", argv[0]);
        fprintf(stderr, "  <fixture> is k1, k2, etc. from kernels_to_trace/build/\n");
        fprintf(stderr, "  example:  sudo %s k1\n", argv[0]);
        return 2;
    }

    /* Resolve fixture path relative to the test binary's working directory. */
    char fixture_path[512];
    snprintf(fixture_path, sizeof(fixture_path),
             "../../../../kernels_to_trace/build/%s", argv[1]);

    if (access(fixture_path, X_OK) != 0) {
        fprintf(stderr, "FAIL: fixture not found or not executable: %s\n",
                fixture_path);
        fprintf(stderr, "  run: make -C kernels_to_trace build\n");
        return 2;
    }

    return test_cu_launch_kernel_emits_identity(fixture_path);
}
