/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // These will be consumed from CSS variables
        bg: 'var(--bg)',
        panel: 'var(--panel)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        text: 'var(--text)',
        'text-dim': 'var(--text-dim)',
        'active-block': 'var(--active-block)',
        'active-text': 'var(--active-text)',
        'chart-line': 'var(--chart-line)',
        ascii: 'var(--ascii)',
        ok: 'var(--ok)',
        warn: 'var(--warn)',
        critical: 'var(--critical)',
        glass: {
          bg: 'var(--glass-bg)',
          border: 'var(--glass-border)',
          'border-strong': 'var(--glass-border-strong)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
      },
      letterSpacing: {
        tight: 'var(--tracking-tight)',
        normal: 'var(--tracking-normal)',
        wide: 'var(--tracking-wide)',
        wider: 'var(--tracking-wider)',
        widest: 'var(--tracking-widest)',
        ultra: 'var(--tracking-ultra)',
        'ultra2': 'var(--tracking-ultra2)',
        'ultra3': 'var(--tracking-ultra3)',
      },
      fontWeight: {
        regular: 'var(--weight-regular)',
        medium: 'var(--weight-medium)',
        semibold: 'var(--weight-semibold)',
        bold: 'var(--weight-bold)',
        extrabold: 'var(--weight-extrabold)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        14: 'var(--space-14)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        'none': 'var(--space-none)',
        'card': 'var(--card-padding)',
        'card-sm': 'var(--card-padding-sm)',
        'panel': 'var(--panel-padding)',
        'page-x': 'var(--page-padding-x)',
        'page-y': 'var(--page-padding-y)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        '4xl': 'var(--radius-4xl)',
        '5xl': 'var(--radius-5xl)',
        '6xl': 'var(--radius-6xl)',
        '7xl': 'var(--radius-7xl)',
        '8xl': 'var(--radius-8xl)',
        '9xl': 'var(--radius-9xl)',
        pill: 'var(--radius-pill)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        none: 'var(--shadow-none)',
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        glass: 'var(--shadow-glass)',
        'glow-sm': 'var(--shadow-glow-sm)',
        'glow-md': 'var(--shadow-glow-md)',
        'glow-lg': 'var(--shadow-glow-lg)',
        'glow-xl': 'var(--shadow-glow-xl)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        base: 'var(--transition-base)',
        slow: 'var(--transition-slow)',
        slower: 'var(--transition-slower)',
        pulse: 'var(--transition-pulse)',
        width: 'var(--transition-width)',
        transform: 'var(--transition-transform)',
        filter: 'var(--transition-filter)',
        color: 'var(--transition-color)',
        border: 'var(--transition-border)',
        background: 'var(--transition-background)',
        opacity: 'var(--transition-opacity)',
      },
      backdropBlur: {
        DEFAULT: 'var(--backdrop-blur)',
        strong: 'var(--backdrop-blur-strong)',
        subtle: 'var(--backdrop-blur-subtle)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        'status-banner': 'var(--z-status-banner)',
        topbar: 'var(--z-topbar)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
        toast: 'var(--z-toast)',
      },
      width: {
        'content': 'var(--max-content-width)',
        'content-narrow': 'var(--max-content-width-narrow)',
      },
      height: {
        topbar: 'var(--topbar-height)',
        'topbar-mobile': 'var(--topbar-height-mobile)',
        subnav: 'var(--subnav-height)',
        'status-banner': 'var(--status-banner-height)',
        sidebar: 'var(--sidebar-width)',
      },
      maxWidth: {
        'page': 'var(--page-max-width)',
        'page-narrow': 'var(--page-max-width-narrow)',
      },
      screens: {
        sm: 'var(--bp-sm)',
        md: 'var(--bp-md)',
        lg: 'var(--bp-lg)',
        xl: 'var(--bp-xl)',
        '2xl': 'var(--bp-2xl)',
        '3xl': 'var(--bp-3xl)',
      },
    },
  },
  plugins: [],
}